name: Push to AWS S3
run-name: ${{ github.actor }} is running this GitHub Actions pipeline 🚀
on: [push]
jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run npm install
        run: npm install
      - name: Run npm build
        run: npm run build
      - name: List the directories
        run: ls
      - name: Configure AWS Credentials 2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

